name: Docker Build and Push

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build application
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./module-39 ./

      - name: Run tests
        run: go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push master tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/module-39:master